### ISSUE TITLE
Change the title to CourseRatings?

### ISSUE THREAD

**Issue by vjampala** [CSE512-15S/a3-emilygu-drapeau-vjampala#2]
I can do it, but I wanted to make sure we were all on board

**Comment by rdrapeau** [comment]
We just need a new img instead of courserankings and then need to change the title in the index.html file.

**Comment by vjampala** [comment]
Oh, dang, didn't realize it was an image. 
Emily, any chance you want to update the image? I'll do all your writing for you~

**Comment by emilygu** [comment]
Wait, I'm confused. Wasn't the storyboard title gonna be incorrect on
purpose?

**Comment by vjampala** [comment]
Oh, I meant the image for the webpage. The title is actually a picture, so we have to make a new one if we want to change it.

**Comment by emilygu** [comment]
Oh, I see what you're saying. If Ryan tells me how to do it, I'll totally
do it. I just don't think he did it on paper.

**Comment by vjampala** [comment]
Oh yeah, I meant using photoshop. I could do it, but it would be in paint, which seems a little less sophisticated..

**Comment by rdrapeau** [comment]
I can change it later today with photoshop. I haven't moved any of the react code over yet, so let me know if you do change it first or it will get overwritten when I build.

**Comment by vjampala** [comment]
Oh, okay, I'll let you do it then! Thanks :)

**Comment by emilygu** [comment]
I don't have photoshop either so you do it
